'use client';

import Link from 'next/link';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { ThemeToggle } from '@/components/theme-toggle';
import {
  Dumbbell,
  Target,
  Sparkles,
  Clock,
  BarChart,
  Heart,
  Zap,
  CheckCircle,
  ArrowRight,
  Users,
  Award,
  Shield
} from 'lucide-react';

export default function LandingPage() {
  const features = [
    {
      icon: Sparkles,
      title: 'AI-Powered Plans',
      description: 'Get personalized workout and diet plans generated by advanced AI technology tailored to your unique goals.'
    },
    {
      icon: Target,
      title: 'Goal-Oriented',
      description: 'Whether you want to lose weight, build muscle, or stay fit, our plans adapt to your specific objectives.'
    },
    {
      icon: Clock,
      title: 'Time Efficient',
      description: 'Workouts designed to fit your schedule. Get results without spending hours at the gym.'
    },
    {
      icon: BarChart,
      title: 'Track Progress',
      description: 'Monitor your journey with detailed tracking and adjust your plan as you achieve milestones.'
    },
    {
      icon: Heart,
      title: 'Health Focused',
      description: 'Plans designed with your overall health and wellness in mind, not just aesthetics.'
    },
    {
      icon: Zap,
      title: 'Instant Results',
      description: 'Get your complete fitness plan in seconds. No waiting, no complicated forms.'
    }
  ];

  const steps = [
    {
      number: '01',
      title: 'Enter Your Details',
      description: 'Share your age, weight, height, fitness level, and goals.'
    },
    {
      number: '02',
      title: 'AI Generates Plan',
      description: 'Our advanced AI creates a personalized workout and diet plan just for you.'
    },
    {
      number: '03',
      title: 'Start Your Journey',
      description: 'Download, save, or listen to your plan and begin transforming your life.'
    }
  ];

  const benefits = [
    {
      icon: Users,
      title: '10,000+ Active Users',
      description: 'Join thousands of people already transforming their lives.'
    },
    {
      icon: Award,
      title: 'Expert-Backed',
      description: 'Plans based on proven fitness and nutrition science.'
    },
    {
      icon: Shield,
      title: '100% Free',
      description: 'No hidden costs, no subscriptions. Completely free forever.'
    },
    {
      icon: CheckCircle,
      title: 'Proven Results',
      description: 'Users report significant improvements in just 4-6 weeks.'
    }
  ];

  return (
    <div className="min-h-screen bg-linear-to-b from-white to-slate-50 dark:from-slate-950 dark:to-slate-900">
      {/* Navigation */}
      <nav className="border-b border-slate-200 dark:border-slate-800 bg-white/80 dark:bg-slate-950/80 backdrop-blur-sm sticky top-0 z-50">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex justify-between items-center h-16">
            <div className="flex items-center space-x-2">
              <div className="w-10 h-10 bg-linear-to-r from-emerald-600 to-teal-600 rounded-lg flex items-center justify-center">
                <Dumbbell className="w-6 h-6 text-white" />
              </div>
              <span className="text-xl font-bold bg-linear-to-r from-emerald-600 to-teal-600 bg-clip-text text-transparent">
                FitAI Coach
              </span>
            </div>
            <div className="flex items-center space-x-4">
              <ThemeToggle />
              <Link href="/app">
                <Button className="bg-linear-to-r from-emerald-600 to-teal-600 hover:from-emerald-700 hover:to-teal-700 text-white">
                  Get Started
                </Button>
              </Link>
            </div>
          </div>
        </div>
      </nav>

      {/* Hero Section */}
      <section className="pt-20 pb-16 px-4 sm:px-6 lg:px-8">
        <div className="max-w-7xl mx-auto text-center">
          <h1 className="text-5xl sm:text-6xl lg:text-7xl font-bold text-slate-900 dark:text-white mb-6">
            Your Personal{' '}
            <span className="bg-linear-to-r from-emerald-600 to-teal-600 bg-clip-text text-transparent">
              FitAI Coach
            </span>
          </h1>
          <p className="text-xl text-slate-600 dark:text-slate-300 mb-8 max-w-3xl mx-auto">
            Transform your body and health with personalized workout and diet plans powered by artificial intelligence. 
            Get started in seconds, completely free.
          </p>
          <div className="flex flex-col sm:flex-row gap-4 justify-center">
            <Link href="/app">
              <Button size="lg" className="bg-linear-to-r from-emerald-600 to-teal-600 hover:from-emerald-700 hover:to-teal-700 text-white text-lg px-8">
                Create Your Plan <ArrowRight className="ml-2 w-5 h-5" />
              </Button>
            </Link>
          </div>

          {/* Stats */}
          <div className="mt-16 grid grid-cols-1 sm:grid-cols-3 gap-8 max-w-3xl mx-auto">
            <div>
              <div className="text-4xl font-bold bg-linear-to-r from-emerald-600 to-teal-600 bg-clip-text text-transparent">
                10K+
              </div>
              <div className="text-slate-600 dark:text-slate-400 mt-2">Active Users</div>
            </div>
            <div>
              <div className="text-4xl font-bold bg-linear-to-r from-emerald-600 to-teal-600 bg-clip-text text-transparent">
                50K+
              </div>
              <div className="text-slate-600 dark:text-slate-400 mt-2">Plans Generated</div>
            </div>
            <div>
              <div className="text-4xl font-bold bg-linear-to-r from-emerald-600 to-teal-600 bg-clip-text text-transparent">
                95%
              </div>
              <div className="text-slate-600 dark:text-slate-400 mt-2">Success Rate</div>
            </div>
          </div>
        </div>
      </section>

      {/* Features Grid */}
      <section className="py-16 px-4 sm:px-6 lg:px-8 bg-white dark:bg-slate-900">
        <div className="max-w-7xl mx-auto">
          <div className="text-center mb-12">
            <h2 className="text-3xl sm:text-4xl font-bold text-slate-900 dark:text-white mb-4">
              Everything You Need to Succeed
            </h2>
            <p className="text-lg text-slate-600 dark:text-slate-300 max-w-2xl mx-auto">
              Our AI-powered platform provides comprehensive fitness solutions tailored to your unique needs.
            </p>
          </div>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
            {features.map((feature, index) => (
              <Card key={index} className="border-slate-200 dark:border-slate-800 hover:shadow-lg transition-shadow">
                <CardHeader>
                  <div className="w-12 h-12 bg-linear-to-r from-emerald-600 to-teal-600 rounded-lg flex items-center justify-center mb-4">
                    <feature.icon className="w-6 h-6 text-white" />
                  </div>
                  <CardTitle className="text-slate-900 dark:text-white">{feature.title}</CardTitle>
                </CardHeader>
                <CardContent>
                  <p className="text-slate-600 dark:text-slate-300">{feature.description}</p>
                </CardContent>
              </Card>
            ))}
          </div>
        </div>
      </section>

      {/* How It Works */}
      <section className="py-16 px-4 sm:px-6 lg:px-8">
        <div className="max-w-7xl mx-auto">
          <div className="text-center mb-12">
            <h2 className="text-3xl sm:text-4xl font-bold text-slate-900 dark:text-white mb-4">
              How It Works
            </h2>
            <p className="text-lg text-slate-600 dark:text-slate-300 max-w-2xl mx-auto">
              Get your personalized fitness plan in three simple steps.
            </p>
          </div>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
            {steps.map((step, index) => (
              <div key={index} className="text-center">
                <div className="w-20 h-20 bg-linear-to-r from-emerald-600 to-teal-600 rounded-full flex items-center justify-center mx-auto mb-6">
                  <span className="text-3xl font-bold text-white">{step.number}</span>
                </div>
                <h3 className="text-xl font-semibold text-slate-900 dark:text-white mb-3">
                  {step.title}
                </h3>
                <p className="text-slate-600 dark:text-slate-300">
                  {step.description}
                </p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* CTA Section */}
      <section className="py-16 px-4 sm:px-6 lg:px-8 bg-linear-to-r from-emerald-600 to-teal-600">
        <div className="max-w-4xl mx-auto text-center">
          <h2 className="text-3xl sm:text-4xl font-bold text-white mb-4">
            Ready to Transform Your Life?
          </h2>
          <p className="text-xl text-emerald-50 mb-8">
            Join thousands of people who have already started their fitness journey with FitAI Coach.
          </p>
          <Link href="/app">
            <Button size="lg" variant="outline" className="bg-white text-emerald-600 hover:bg-emerald-50 border-0 text-lg px-8">
              Get Your Free Plan Now <ArrowRight className="ml-2 w-5 h-5" />
            </Button>
          </Link>
        </div>
      </section>

      {/* Why Choose Us */}
      <section className="py-16 px-4 sm:px-6 lg:px-8 bg-white dark:bg-slate-900">
        <div className="max-w-7xl mx-auto">
          <div className="text-center mb-12">
            <h2 className="text-3xl sm:text-4xl font-bold text-slate-900 dark:text-white mb-4">
              Why Choose FitAI Coach?
            </h2>
          </div>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8">
            {benefits.map((benefit, index) => (
              <div key={index} className="text-center">
                <div className="w-16 h-16 bg-linear-to-r from-emerald-600 to-teal-600 rounded-lg flex items-center justify-center mx-auto mb-4">
                  <benefit.icon className="w-8 h-8 text-white" />
                </div>
                <h3 className="text-lg font-semibold text-slate-900 dark:text-white mb-2">
                  {benefit.title}
                </h3>
                <p className="text-slate-600 dark:text-slate-300 text-sm">
                  {benefit.description}
                </p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Footer */}
      <footer className="border-t border-slate-200 dark:border-slate-800 py-12 px-4 sm:px-6 lg:px-8">
        <div className="max-w-7xl mx-auto">
          <div className="flex flex-col md:flex-row justify-between items-center">
            <div className="flex items-center space-x-2 mb-4 md:mb-0">
              <div className="w-10 h-10 bg-linear-to-r from-emerald-600 to-teal-600 rounded-lg flex items-center justify-center">
                <Dumbbell className="w-6 h-6 text-white" />
              </div>
              <span className="text-xl font-bold bg-linear-to-r from-emerald-600 to-teal-600 bg-clip-text text-transparent">
                FitAI Coach
              </span>
            </div>
            <div className="text-slate-600 dark:text-slate-400 text-sm">
              © 2024 FitAI Coach. All rights reserved.
            </div>
          </div>
        </div>
      </footer>
    </div>
  );
}
